name: Build PR

on: [ pull_request ]

jobs:
  build_pr:
    if: github.repository_owner == 'IntellectualSites'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Clean Build
        run: ./gradlew clean build
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Test Results ${{ matrix.os }}
          path: Core/build/test-results/test/*.xml

  publish-test-results:
    name: "Publish Tests Results"
    needs: build_pr
    runs-on: ubuntu-latest
    permissions:
      checks: write
    if: always()
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          junit_files: Core/build/test-results/test/*.xml
